# The URL the site will be built for
base_url = "https://developmeh.com"
title = "DevelopMeh"
author = "paul@scarrone.co"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "zola_easydocs_theme"

feed_filenames = ["rss.xml", "atom.xml"]
generate_feeds = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
extra_syntaxes_and_themes = ["syntaxes", "syntaxes/glowfish_contrast"]
highlight_theme = "ruby"

[extra]
# Put all your custom variables here
force_link = false
favicon = "favicon.ico"
keywords = "golang, ruby, software-development, devex, software-architecture, education, editorial"
desc = "Contained within are harebrained ideas that have no commercial value... still here... you are one of the special ones."
# Default image for Open Graph and Twitter cards if not specified in page frontmatter
default_og_image = "favicon.ico"
# Logo for structured data
logo = ""
# Author information
author_url = "https://developmeh.com/about"
author_image = "favicon.ico"
author_job_title = "Developer"
# Social profiles for sameAs in structured data
social_profiles = [
  "https://github.com/developmeh",
  "https://twitter.com/developmeh"
]
# Business information (uncomment and fill if applicable)
# business_info = true
# business_type = "Organization" # or other schema.org business types like LocalBusiness, etc.
# business_email = "contact@example.com"
# business_telephone = "+1234567890"
# [extra.business_address]
# street = "123 Main St"
# city = "Anytown"
# region = "State"
# postal_code = "12345"
# country = "US"
